name: SonarCloud

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      VITE_APPLICATION_NAME: Ragnarok Utilities
      VITE_BASE_PATH: /
      VITE_PARSER_URL: https://localhost:3000/parse
      VITE_REPLAY_URL_SHARE: /replay-parser/ID_HERE
      VITE_SKILL_IMAGE_URL: https://static.divine-pride.net/images/skill/PLACEHOLDER_TEXT.png
      VITE_JOB_IMAGE_URL: https://static.divine-pride.net/images/jobs/icon_jobs_PLACEHOLDER_TEXT.png
      VITE_MONSTER_IMAGE_URL: https://talontales.com/panel/data/monsters/PLACEHOLDER_TEXT.gif
      VITE_ITEM_IMAGE_URL: https://static.divine-pride.net/images/items/item/PLACEHOLDER_TEXT.png
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci --ignore-scripts
      - run: npm run test:coverage

      - uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
